# Generated by Django 2.1.2 on 2018-10-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_in', models.PositiveIntegerField()),
                ('power_out', models.PositiveIntegerField()),
                ('enabled', models.BooleanField(default=False)),
                ('surge_multiplier', models.PositiveIntegerField(default=1)),
                ('base_cost_per_unit', models.DecimalField(decimal_places=2, default=0.1, max_digits=6)),
                ('neighbor_ids', models.ManyToManyField(related_name='neighbor', to='api.Node')),
            ],
        ),
    ]
