# Generated by Django 2.1.2 on 2018-10-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='base_cost_per_unit',
        ),
        migrations.RemoveField(
            model_name='node',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='node',
            name='power_in',
        ),
        migrations.RemoveField(
            model_name='node',
            name='power_out',
        ),
        migrations.RemoveField(
            model_name='node',
            name='surge_multiplier',
        ),
        migrations.AddField(
            model_name='node',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='cost_per_unit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='node',
            name='flow',
            field=models.IntegerField(default=0),
        ),
    ]
